"""Alembic migration script template."""

"""change_source_message_id_to_varchar

Revision ID: a8ca4893d0fa
Revises: a0f22adf1f56
Create Date: 2026-01-15 06:04:17.930836+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'a8ca4893d0fa'
down_revision = 'a0f22adf1f56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only alter source_message_id column - ignore auto-detected table drops
    op.alter_column('jobs', 'source_message_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'source_message_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
    op.alter_column('students', 'profile_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('jobs', 'source_message_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('jobs', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('telegram_groups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('members_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_joined', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('joined_by_account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_message_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_message_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('messages_fetched_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_messages_scraped', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_messages_found', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quality_jobs_found', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_job_posted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deactivated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deactivation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telegram_groups_pkey')
    )
    op.create_index('ix_telegram_groups_username', 'telegram_groups', ['username'], unique=True)
    op.create_table('raw_telegram_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('group_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sender_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('message_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('has_media', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='raw_telegram_messages_pkey'),
    comment='Raw messages fetched from Telegram channels before AI processing'
    )
    op.create_index('ix_raw_telegram_messages_processed', 'raw_telegram_messages', ['processed'], unique=False)
    op.create_index('ix_raw_telegram_messages_group_username', 'raw_telegram_messages', ['group_username'], unique=False)
    op.create_table('job_scraping_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allowed_job_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('excluded_job_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('min_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accept_unspecified_experience', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allowed_education_levels', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('allow_all_india', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allow_international', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allowed_work_modes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('priority_skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('excluded_skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('min_salary_lpa', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_salary_lpa', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('filter_by_salary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('excluded_companies', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('preferred_companies', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('required_keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('excluded_keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('min_ai_confidence_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_messages_per_run', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skip_duplicate_threshold_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='job_scraping_preferences_pkey')
    )
    op.create_index('idx_job_prefs_active_unique', 'job_scraping_preferences', ['is_active'], unique=True, postgresql_where='(is_active = true)')
    op.create_table('scraping_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lambda_function', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('accounts_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('groups_processed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('messages_fetched', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jobs_extracted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duplicates_found', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('errors_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cost_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scraping_logs_pkey')
    )
    op.create_index('ix_scraping_logs_lambda_function', 'scraping_logs', ['lambda_function'], unique=False)
    op.create_table('telegram_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('api_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('session_string', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('groups_joined_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_join_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telegram_accounts_pkey')
    )
    op.create_index('ix_telegram_accounts_phone', 'telegram_accounts', ['phone'], unique=True)
    # ### end Alembic commands ###
