#!/bin/bash
#
# Setup ML Processing Cron Jobs
# Automates:
# 1. Daily ML processing at 6 AM IST (after 5 AM Lambda scrape)
# 2. Weekly model retraining on Sunday 2 AM IST
#

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get script directory and project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

echo "=================================================================================================="
echo "🕐 ML Processing Cron Job Setup"
echo "=================================================================================================="
echo "This will setup automated ML processing:"
echo "  1. Daily ML processing: 6:00 AM IST (0:30 AM UTC)"
echo "  2. Weekly retraining: Sunday 2:00 AM IST (Saturday 8:30 PM UTC)"
echo "=================================================================================================="
echo ""

# Check if Python 3 is available
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Error: python3 not found${NC}"
    exit 1
fi

# Check if project files exist
if [ ! -f "$PROJECT_ROOT/scripts/run_ml_pipeline.py" ]; then
    echo -e "${RED}❌ Error: run_ml_pipeline.py not found${NC}"
    exit 1
fi

if [ ! -f "$PROJECT_ROOT/scripts/retrain_model.py" ]; then
    echo -e "${RED}❌ Error: retrain_model.py not found${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Found required scripts${NC}"
echo ""

# Get Python path
PYTHON_PATH=$(which python3)
echo "Python path: $PYTHON_PATH"
echo "Project root: $PROJECT_ROOT"
echo ""

# Create wrapper scripts for cron (cron has limited PATH)
echo "📝 Creating wrapper scripts..."

# Daily ML processing wrapper
cat > "$PROJECT_ROOT/scripts/cron_run_ml_pipeline.sh" << EOF
#!/bin/bash
# Auto-generated by setup_ml_cron.sh
# Daily ML processing wrapper for cron

cd $PROJECT_ROOT
$PYTHON_PATH $PROJECT_ROOT/scripts/run_ml_pipeline.py >> $PROJECT_ROOT/logs/ml_processing_cron.log 2>&1
EOF

chmod +x "$PROJECT_ROOT/scripts/cron_run_ml_pipeline.sh"
echo -e "${GREEN}✅ Created cron_run_ml_pipeline.sh${NC}"

# Weekly retraining wrapper
cat > "$PROJECT_ROOT/scripts/cron_retrain_model.sh" << EOF
#!/bin/bash
# Auto-generated by setup_ml_cron.sh
# Weekly model retraining wrapper for cron

cd $PROJECT_ROOT
$PYTHON_PATH $PROJECT_ROOT/scripts/retrain_model.py >> $PROJECT_ROOT/logs/ml_retraining_cron.log 2>&1
EOF

chmod +x "$PROJECT_ROOT/scripts/cron_retrain_model.sh"
echo -e "${GREEN}✅ Created cron_retrain_model.sh${NC}"
echo ""

# Create logs directory if it doesn't exist
mkdir -p "$PROJECT_ROOT/logs"
touch "$PROJECT_ROOT/logs/ml_processing_cron.log"
touch "$PROJECT_ROOT/logs/ml_retraining_cron.log"
echo -e "${GREEN}✅ Created log files${NC}"
echo ""

# Generate crontab entries
echo "📋 Generating crontab entries..."
echo ""

CRON_ENTRIES=$(cat << EOF
# ML Processing Pipeline - Auto-generated by setup_ml_cron.sh
# Daily ML processing at 6:00 AM IST (0:30 AM UTC)
30 0 * * * $PROJECT_ROOT/scripts/cron_run_ml_pipeline.sh

# Weekly model retraining on Sunday 2:00 AM IST (Saturday 8:30 PM UTC)
30 20 * * 6 $PROJECT_ROOT/scripts/cron_retrain_model.sh
EOF
)

echo "$CRON_ENTRIES"
echo ""

# Backup existing crontab
echo "💾 Backing up existing crontab..."
crontab -l > "$PROJECT_ROOT/crontab_backup_$(date +%Y%m%d_%H%M%S).txt" 2>/dev/null || echo "No existing crontab found"

# Ask user for confirmation
echo ""
echo -e "${YELLOW}⚠️  This will add the above cron jobs to your crontab.${NC}"
read -p "Do you want to continue? (y/N) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Add to crontab
    (crontab -l 2>/dev/null || echo ""; echo ""; echo "$CRON_ENTRIES") | crontab -
    
    echo ""
    echo -e "${GREEN}✅ Cron jobs installed successfully!${NC}"
    echo ""
    echo "=================================================================================================="
    echo "📋 Installed Cron Jobs:"
    echo "=================================================================================================="
    crontab -l | grep -A2 "ML Processing Pipeline"
    echo ""
    echo "=================================================================================================="
    echo "📊 Schedule Summary:"
    echo "=================================================================================================="
    echo "Daily ML Processing:"
    echo "  • Time: 6:00 AM IST (0:30 AM UTC)"
    echo "  • Action: Process unprocessed Telegram messages"
    echo "  • Log: $PROJECT_ROOT/logs/ml_processing_cron.log"
    echo ""
    echo "Weekly Model Retraining:"
    echo "  • Time: Sunday 2:00 AM IST (Saturday 8:30 PM UTC)"
    echo "  • Action: Retrain ML model with latest training data"
    echo "  • Log: $PROJECT_ROOT/logs/ml_retraining_cron.log"
    echo "=================================================================================================="
    echo ""
    echo "🔍 Useful Commands:"
    echo "  • View crontab:           crontab -l"
    echo "  • Edit crontab:           crontab -e"
    echo "  • Remove crontab:         crontab -r"
    echo "  • View processing log:    tail -f $PROJECT_ROOT/logs/ml_processing_cron.log"
    echo "  • View retraining log:    tail -f $PROJECT_ROOT/logs/ml_retraining_cron.log"
    echo "  • Test ML pipeline:       $PROJECT_ROOT/scripts/run_ml_pipeline.py"
    echo "  • Test retraining:        $PROJECT_ROOT/scripts/retrain_model.py"
    echo ""
    echo "🎯 Next Steps:"
    echo "  1. Test the ML pipeline manually: python3 scripts/run_ml_pipeline.py"
    echo "  2. Check cron logs tomorrow: tail logs/ml_processing_cron.log"
    echo "  3. Monitor job creation in PostgreSQL"
    echo ""
    echo -e "${GREEN}✅ Setup complete!${NC}"
    
else
    echo ""
    echo -e "${YELLOW}⚠️  Cron installation cancelled${NC}"
    echo ""
    echo "You can manually add these entries to crontab with: crontab -e"
    echo "Or run this script again when ready."
fi

echo ""
